import Head from "next/head";
import { Inter } from "next/font/google";
import HomeLayout from "@/src/components/Home/HomeLayout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Farhad</title>
        <meta name="description" content="Generated by farhad" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeLayout />
      </main>
    </>
  );
}
